// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: match.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C2S 300--400
// S2C 400--500
type MatchPlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	IsRobot       bool                   `protobuf:"varint,2,opt,name=isRobot,proto3" json:"isRobot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPlayerInfo) Reset() {
	*x = MatchPlayerInfo{}
	mi := &file_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPlayerInfo) ProtoMessage() {}

func (x *MatchPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPlayerInfo.ProtoReflect.Descriptor instead.
func (*MatchPlayerInfo) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchPlayerInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MatchPlayerInfo) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

type C2S_StartMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_StartMatch) Reset() {
	*x = C2S_StartMatch{}
	mi := &file_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_StartMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_StartMatch) ProtoMessage() {}

func (x *C2S_StartMatch) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_StartMatch.ProtoReflect.Descriptor instead.
func (*C2S_StartMatch) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_StartMatch) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type S2C_StartMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_StartMatch) Reset() {
	*x = S2C_StartMatch{}
	mi := &file_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_StartMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_StartMatch) ProtoMessage() {}

func (x *S2C_StartMatch) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_StartMatch.ProtoReflect.Descriptor instead.
func (*S2C_StartMatch) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_StartMatch) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type S2C_MatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerInfos   []*MatchPlayerInfo     `protobuf:"bytes,2,rep,name=playerInfos,proto3" json:"playerInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_MatchResult) Reset() {
	*x = S2C_MatchResult{}
	mi := &file_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MatchResult) ProtoMessage() {}

func (x *S2C_MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MatchResult.ProtoReflect.Descriptor instead.
func (*S2C_MatchResult) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_MatchResult) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *S2C_MatchResult) GetPlayerInfos() []*MatchPlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type C2S_CancelMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_CancelMatch) Reset() {
	*x = C2S_CancelMatch{}
	mi := &file_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_CancelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CancelMatch) ProtoMessage() {}

func (x *C2S_CancelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CancelMatch.ProtoReflect.Descriptor instead.
func (*C2S_CancelMatch) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{4}
}

type S2C_CancelMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_CancelMatch) Reset() {
	*x = S2C_CancelMatch{}
	mi := &file_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_CancelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CancelMatch) ProtoMessage() {}

func (x *S2C_CancelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CancelMatch.ProtoReflect.Descriptor instead.
func (*S2C_CancelMatch) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_CancelMatch) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type S2C_PlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_PlayerOffline) Reset() {
	*x = S2C_PlayerOffline{}
	mi := &file_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerOffline) ProtoMessage() {}

func (x *S2C_PlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerOffline.ProtoReflect.Descriptor instead.
func (*S2C_PlayerOffline) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_PlayerOffline) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// ---------------room-----------
type C2S_RecordGameOperate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	OperateInfo   string                 `protobuf:"bytes,2,opt,name=operateInfo,proto3" json:"operateInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_RecordGameOperate) Reset() {
	*x = C2S_RecordGameOperate{}
	mi := &file_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_RecordGameOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RecordGameOperate) ProtoMessage() {}

func (x *C2S_RecordGameOperate) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RecordGameOperate.ProtoReflect.Descriptor instead.
func (*C2S_RecordGameOperate) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_RecordGameOperate) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *C2S_RecordGameOperate) GetOperateInfo() string {
	if x != nil {
		return x.OperateInfo
	}
	return ""
}

type S2C_RecordGameOperate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperateInfo   string                 `protobuf:"bytes,1,opt,name=operateInfo,proto3" json:"operateInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_RecordGameOperate) Reset() {
	*x = S2C_RecordGameOperate{}
	mi := &file_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RecordGameOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RecordGameOperate) ProtoMessage() {}

func (x *S2C_RecordGameOperate) ProtoReflect() protoreflect.Message {
	mi := &file_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RecordGameOperate.ProtoReflect.Descriptor instead.
func (*S2C_RecordGameOperate) Descriptor() ([]byte, []int) {
	return file_match_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_RecordGameOperate) GetOperateInfo() string {
	if x != nil {
		return x.OperateInfo
	}
	return ""
}

var File_match_proto protoreflect.FileDescriptor

const file_match_proto_rawDesc = "" +
	"\n" +
	"\vmatch.proto\x1a\x10message_id.proto\"G\n" +
	"\x0fMatchPlayerInfo\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12\x18\n" +
	"\aisRobot\x18\x02 \x01(\bR\aisRobot\"+\n" +
	"\x0eC2S_StartMatch\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type:\x05\x80\xb5\x18\xad\x02\"/\n" +
	"\x0eS2C_StartMatch\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result:\x05\x80\xb5\x18\x91\x03\"d\n" +
	"\x0fS2C_MatchResult\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x122\n" +
	"\vplayerInfos\x18\x02 \x03(\v2\x10.MatchPlayerInfoR\vplayerInfos:\x05\x80\xb5\x18\x92\x03\"\x18\n" +
	"\x0fC2S_CancelMatch:\x05\x80\xb5\x18\xaf\x02\"0\n" +
	"\x0fS2C_CancelMatch\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result:\x05\x80\xb5\x18\x93\x03\"6\n" +
	"\x11S2C_PlayerOffline\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId:\x05\x80\xb5\x18\x93\x03\"X\n" +
	"\x15C2S_RecordGameOperate\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12 \n" +
	"\voperateInfo\x18\x02 \x01(\tR\voperateInfo:\x05\x80\xb5\x18\xb0\x02\"@\n" +
	"\x15S2C_RecordGameOperate\x12 \n" +
	"\voperateInfo\x18\x01 \x01(\tR\voperateInfo:\x05\x80\xb5\x18\x94\x03B\x0eZ\f./../messageb\x06proto3"

var (
	file_match_proto_rawDescOnce sync.Once
	file_match_proto_rawDescData []byte
)

func file_match_proto_rawDescGZIP() []byte {
	file_match_proto_rawDescOnce.Do(func() {
		file_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)))
	})
	return file_match_proto_rawDescData
}

var file_match_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_match_proto_goTypes = []any{
	(*MatchPlayerInfo)(nil),       // 0: MatchPlayerInfo
	(*C2S_StartMatch)(nil),        // 1: C2S_StartMatch
	(*S2C_StartMatch)(nil),        // 2: S2C_StartMatch
	(*S2C_MatchResult)(nil),       // 3: S2C_MatchResult
	(*C2S_CancelMatch)(nil),       // 4: C2S_CancelMatch
	(*S2C_CancelMatch)(nil),       // 5: S2C_CancelMatch
	(*S2C_PlayerOffline)(nil),     // 6: S2C_PlayerOffline
	(*C2S_RecordGameOperate)(nil), // 7: C2S_RecordGameOperate
	(*S2C_RecordGameOperate)(nil), // 8: S2C_RecordGameOperate
}
var file_match_proto_depIdxs = []int32{
	0, // 0: S2C_MatchResult.playerInfos:type_name -> MatchPlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_match_proto_init() }
func file_match_proto_init() {
	if File_match_proto != nil {
		return
	}
	file_message_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_proto_rawDesc), len(file_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_proto_goTypes,
		DependencyIndexes: file_match_proto_depIdxs,
		MessageInfos:      file_match_proto_msgTypes,
	}.Build()
	File_match_proto = out.File
	file_match_proto_goTypes = nil
	file_match_proto_depIdxs = nil
}
