// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: message_id.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_message_id_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50000,
		Name:          "message_id",
		Tag:           "varint,50000,opt,name=message_id",
		Filename:      "message_id.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 message_id = 50000;
	E_MessageId = &file_message_id_proto_extTypes[0] // 使用高编号的字段ID（50000-99999）
)

var File_message_id_proto protoreflect.FileDescriptor

const file_message_id_proto_rawDesc = "" +
	"\n" +
	"\x10message_id.proto\x1a google/protobuf/descriptor.proto:@\n" +
	"\n" +
	"message_id\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\rR\tmessageIdB\x0eZ\f./../messageb\x06proto3"

var file_message_id_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_message_id_proto_depIdxs = []int32{
	0, // 0: message_id:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_id_proto_init() }
func file_message_id_proto_init() {
	if File_message_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_id_proto_rawDesc), len(file_message_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_message_id_proto_goTypes,
		DependencyIndexes: file_message_id_proto_depIdxs,
		ExtensionInfos:    file_message_id_proto_extTypes,
	}.Build()
	File_message_id_proto = out.File
	file_message_id_proto_goTypes = nil
	file_message_id_proto_depIdxs = nil
}
