// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: rank/rank.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取排行榜
type C2S_GetRankList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"` // 排行榜类型：1-等级榜，2-战力榜，3-财富榜
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`         // 页码，从1开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GetRankList) Reset() {
	*x = C2S_GetRankList{}
	mi := &file_rank_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GetRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetRankList) ProtoMessage() {}

func (x *C2S_GetRankList) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetRankList.ProtoReflect.Descriptor instead.
func (*C2S_GetRankList) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_GetRankList) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *C2S_GetRankList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *C2S_GetRankList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type S2C_GetRankList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"`
	RankItems     []*RankItem            `protobuf:"bytes,2,rep,name=rankItems,proto3" json:"rankItems,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GetRankList) Reset() {
	*x = S2C_GetRankList{}
	mi := &file_rank_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GetRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetRankList) ProtoMessage() {}

func (x *S2C_GetRankList) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetRankList.ProtoReflect.Descriptor instead.
func (*S2C_GetRankList) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_GetRankList) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *S2C_GetRankList) GetRankItems() []*RankItem {
	if x != nil {
		return x.RankItems
	}
	return nil
}

func (x *S2C_GetRankList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *S2C_GetRankList) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

// 排行榜项目
type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`  // 分数/等级/战力/财富等
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"` // 头像
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`  // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_rank_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{2}
}

func (x *RankItem) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RankItem) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *RankItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RankItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 获取我的排名
type C2S_GetMyRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GetMyRank) Reset() {
	*x = C2S_GetMyRank{}
	mi := &file_rank_rank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GetMyRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetMyRank) ProtoMessage() {}

func (x *C2S_GetMyRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetMyRank.ProtoReflect.Descriptor instead.
func (*C2S_GetMyRank) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_GetMyRank) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

type S2C_GetMyRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"`
	MyRank        int32                  `protobuf:"varint,2,opt,name=myRank,proto3" json:"myRank,omitempty"`
	MyScore       int64                  `protobuf:"varint,3,opt,name=myScore,proto3" json:"myScore,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GetMyRank) Reset() {
	*x = S2C_GetMyRank{}
	mi := &file_rank_rank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GetMyRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetMyRank) ProtoMessage() {}

func (x *S2C_GetMyRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetMyRank.ProtoReflect.Descriptor instead.
func (*S2C_GetMyRank) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_GetMyRank) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *S2C_GetMyRank) GetMyRank() int32 {
	if x != nil {
		return x.MyRank
	}
	return 0
}

func (x *S2C_GetMyRank) GetMyScore() int64 {
	if x != nil {
		return x.MyScore
	}
	return 0
}

func (x *S2C_GetMyRank) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 更新排行榜数据
type C2S_UpdateRankData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rankType,proto3" json:"rankType,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_UpdateRankData) Reset() {
	*x = C2S_UpdateRankData{}
	mi := &file_rank_rank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_UpdateRankData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_UpdateRankData) ProtoMessage() {}

func (x *C2S_UpdateRankData) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_UpdateRankData.ProtoReflect.Descriptor instead.
func (*C2S_UpdateRankData) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_UpdateRankData) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *C2S_UpdateRankData) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type S2C_UpdateRankData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewRank       int32                  `protobuf:"varint,2,opt,name=newRank,proto3" json:"newRank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_UpdateRankData) Reset() {
	*x = S2C_UpdateRankData{}
	mi := &file_rank_rank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_UpdateRankData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_UpdateRankData) ProtoMessage() {}

func (x *S2C_UpdateRankData) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_UpdateRankData.ProtoReflect.Descriptor instead.
func (*S2C_UpdateRankData) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_UpdateRankData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_UpdateRankData) GetNewRank() int32 {
	if x != nil {
		return x.NewRank
	}
	return 0
}

var File_rank_rank_proto protoreflect.FileDescriptor

const file_rank_rank_proto_rawDesc = "" +
	"\n" +
	"\x0frank/rank.proto\x1a\x10message_id.proto\"d\n" +
	"\x0fC2S_GetRankList\x12\x1a\n" +
	"\brankType\x18\x01 \x01(\x05R\brankType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize:\x05\x80\xb5\x18\xf5\x03\"\x9f\x01\n" +
	"\x0fS2C_GetRankList\x12\x1a\n" +
	"\brankType\x18\x01 \x01(\x05R\brankType\x12'\n" +
	"\trankItems\x18\x02 \x03(\v2\t.RankItemR\trankItems\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x03 \x01(\x05R\n" +
	"totalCount\x12 \n" +
	"\vcurrentPage\x18\x04 \x01(\x05R\vcurrentPage:\x05\x80\xb5\x18\xd9\x04\"\x9e\x01\n" +
	"\bRankItem\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x03R\bplayerId\x12\x1e\n" +
	"\n" +
	"playerName\x18\x02 \x01(\tR\n" +
	"playerName\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\"2\n" +
	"\rC2S_GetMyRank\x12\x1a\n" +
	"\brankType\x18\x01 \x01(\x05R\brankType:\x05\x80\xb5\x18\xf6\x03\"\x84\x01\n" +
	"\rS2C_GetMyRank\x12\x1a\n" +
	"\brankType\x18\x01 \x01(\x05R\brankType\x12\x16\n" +
	"\x06myRank\x18\x02 \x01(\x05R\x06myRank\x12\x18\n" +
	"\amyScore\x18\x03 \x01(\x03R\amyScore\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x04 \x01(\x05R\n" +
	"totalCount:\x05\x80\xb5\x18\xda\x04\"M\n" +
	"\x12C2S_UpdateRankData\x12\x1a\n" +
	"\brankType\x18\x01 \x01(\x05R\brankType\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score:\x05\x80\xb5\x18\xf7\x03\"O\n" +
	"\x12S2C_UpdateRankData\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\anewRank\x18\x02 \x01(\x05R\anewRank:\x05\x80\xb5\x18\xdb\x04B\x0eZ\f./../messageb\x06proto3"

var (
	file_rank_rank_proto_rawDescOnce sync.Once
	file_rank_rank_proto_rawDescData []byte
)

func file_rank_rank_proto_rawDescGZIP() []byte {
	file_rank_rank_proto_rawDescOnce.Do(func() {
		file_rank_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_rank_proto_rawDesc), len(file_rank_rank_proto_rawDesc)))
	})
	return file_rank_rank_proto_rawDescData
}

var file_rank_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rank_rank_proto_goTypes = []any{
	(*C2S_GetRankList)(nil),    // 0: C2S_GetRankList
	(*S2C_GetRankList)(nil),    // 1: S2C_GetRankList
	(*RankItem)(nil),           // 2: RankItem
	(*C2S_GetMyRank)(nil),      // 3: C2S_GetMyRank
	(*S2C_GetMyRank)(nil),      // 4: S2C_GetMyRank
	(*C2S_UpdateRankData)(nil), // 5: C2S_UpdateRankData
	(*S2C_UpdateRankData)(nil), // 6: S2C_UpdateRankData
}
var file_rank_rank_proto_depIdxs = []int32{
	2, // 0: S2C_GetRankList.rankItems:type_name -> RankItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rank_rank_proto_init() }
func file_rank_rank_proto_init() {
	if File_rank_rank_proto != nil {
		return
	}
	file_message_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_rank_proto_rawDesc), len(file_rank_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_rank_proto_goTypes,
		DependencyIndexes: file_rank_rank_proto_depIdxs,
		MessageInfos:      file_rank_rank_proto_msgTypes,
	}.Build()
	File_rank_rank_proto = out.File
	file_rank_rank_proto_goTypes = nil
	file_rank_rank_proto_depIdxs = nil
}
