// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: game/recharge.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付平台
type PaymentPlatform int32

const (
	PaymentPlatform_Platform_None   PaymentPlatform = 0
	PaymentPlatform_Platform_WeChat PaymentPlatform = 1
	PaymentPlatform_Platform_AliPay PaymentPlatform = 2
	PaymentPlatform_Platform_DouYin PaymentPlatform = 3
)

// Enum value maps for PaymentPlatform.
var (
	PaymentPlatform_name = map[int32]string{
		0: "Platform_None",
		1: "Platform_WeChat",
		2: "Platform_AliPay",
		3: "Platform_DouYin",
	}
	PaymentPlatform_value = map[string]int32{
		"Platform_None":   0,
		"Platform_WeChat": 1,
		"Platform_AliPay": 2,
		"Platform_DouYin": 3,
	}
)

func (x PaymentPlatform) Enum() *PaymentPlatform {
	p := new(PaymentPlatform)
	*p = x
	return p
}

func (x PaymentPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_game_recharge_proto_enumTypes[0].Descriptor()
}

func (PaymentPlatform) Type() protoreflect.EnumType {
	return &file_game_recharge_proto_enumTypes[0]
}

func (x PaymentPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentPlatform.Descriptor instead.
func (PaymentPlatform) EnumDescriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{0}
}

// 充值配置
type RechargeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 配置ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 充值包名称
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                        // 充值金额（分）
	Bonus         int64                  `protobuf:"varint,4,opt,name=bonus,proto3" json:"bonus,omitempty"`                          // 赠送金额（分）
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                     // 货币类型
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`    // 是否激活
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeConfig) Reset() {
	*x = RechargeConfig{}
	mi := &file_game_recharge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeConfig) ProtoMessage() {}

func (x *RechargeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeConfig.ProtoReflect.Descriptor instead.
func (*RechargeConfig) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RechargeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RechargeConfig) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeConfig) GetBonus() int64 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *RechargeConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RechargeConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RechargeConfig) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RechargeConfig) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 充值记录
type RechargeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 充值订单ID
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`               // 玩家ID
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`             // 账户ID
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 充值金额（分）
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                // 货币类型
	Platform      int32                  `protobuf:"varint,6,opt,name=platform,proto3" json:"platform,omitempty"`                               // 支付平台
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                   // 充值状态 0:待处理 1:成功 2:失败 3:已取消
	OrderId       string                 `protobuf:"bytes,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // 第三方订单ID
	TransactionId string                 `protobuf:"bytes,9,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 交易流水号
	CreateTime    int64                  `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`        // 创建时间
	UpdateTime    int64                  `protobuf:"varint,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`        // 更新时间
	CompleteTime  int64                  `protobuf:"varint,12,opt,name=complete_time,json=completeTime,proto3" json:"complete_time,omitempty"`  // 完成时间
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`                         // 充值描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRecord) Reset() {
	*x = RechargeRecord{}
	mi := &file_game_recharge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRecord) ProtoMessage() {}

func (x *RechargeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRecord.ProtoReflect.Descriptor instead.
func (*RechargeRecord) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RechargeRecord) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RechargeRecord) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RechargeRecord) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RechargeRecord) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *RechargeRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RechargeRecord) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RechargeRecord) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RechargeRecord) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RechargeRecord) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *RechargeRecord) GetCompleteTime() int64 {
	if x != nil {
		return x.CompleteTime
	}
	return 0
}

func (x *RechargeRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 充值请求
type C2S_RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"` // 充值金额（分）
	Platform      PaymentPlatform        `protobuf:"varint,2,opt,name=platform,proto3,enum=PaymentPlatform" json:"platform,omitempty"`
	ConfigId      string                 `protobuf:"bytes,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // 充值配置ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_RechargeRequest) Reset() {
	*x = C2S_RechargeRequest{}
	mi := &file_game_recharge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RechargeRequest) ProtoMessage() {}

func (x *C2S_RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RechargeRequest.ProtoReflect.Descriptor instead.
func (*C2S_RechargeRequest) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_RechargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *C2S_RechargeRequest) GetPlatform() PaymentPlatform {
	if x != nil {
		return x.Platform
	}
	return PaymentPlatform_Platform_None
}

func (x *C2S_RechargeRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

// 充值响应
type S2C_RechargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`          // 订单ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // 消息
	PaymentUrl    string                 `protobuf:"bytes,4,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // 支付链接
	QrCode        string                 `protobuf:"bytes,5,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`             // 二维码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_RechargeResponse) Reset() {
	*x = S2C_RechargeResponse{}
	mi := &file_game_recharge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RechargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RechargeResponse) ProtoMessage() {}

func (x *S2C_RechargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RechargeResponse.ProtoReflect.Descriptor instead.
func (*S2C_RechargeResponse) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_RechargeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_RechargeResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *S2C_RechargeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S2C_RechargeResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *S2C_RechargeResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

// 充值成功通知
type S2C_RechargeSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`              // 订单ID
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                              // 充值金额
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 总金额（含赠送）
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`                            // 当前余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_RechargeSuccess) Reset() {
	*x = S2C_RechargeSuccess{}
	mi := &file_game_recharge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_RechargeSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RechargeSuccess) ProtoMessage() {}

func (x *S2C_RechargeSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RechargeSuccess.ProtoReflect.Descriptor instead.
func (*S2C_RechargeSuccess) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_RechargeSuccess) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *S2C_RechargeSuccess) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *S2C_RechargeSuccess) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *S2C_RechargeSuccess) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 获取充值配置请求
type C2S_GetRechargeConfigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GetRechargeConfigs) Reset() {
	*x = C2S_GetRechargeConfigs{}
	mi := &file_game_recharge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GetRechargeConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetRechargeConfigs) ProtoMessage() {}

func (x *C2S_GetRechargeConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetRechargeConfigs.ProtoReflect.Descriptor instead.
func (*C2S_GetRechargeConfigs) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{5}
}

// 获取充值配置响应
type S2C_GetRechargeConfigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*RechargeConfig      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GetRechargeConfigs) Reset() {
	*x = S2C_GetRechargeConfigs{}
	mi := &file_game_recharge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GetRechargeConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetRechargeConfigs) ProtoMessage() {}

func (x *S2C_GetRechargeConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetRechargeConfigs.ProtoReflect.Descriptor instead.
func (*S2C_GetRechargeConfigs) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_GetRechargeConfigs) GetConfigs() []*RechargeConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

// 获取充值记录请求
type C2S_GetRechargeRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 限制数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GetRechargeRecords) Reset() {
	*x = C2S_GetRechargeRecords{}
	mi := &file_game_recharge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GetRechargeRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetRechargeRecords) ProtoMessage() {}

func (x *C2S_GetRechargeRecords) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetRechargeRecords.ProtoReflect.Descriptor instead.
func (*C2S_GetRechargeRecords) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_GetRechargeRecords) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取充值记录响应
type S2C_GetRechargeRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RechargeRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GetRechargeRecords) Reset() {
	*x = S2C_GetRechargeRecords{}
	mi := &file_game_recharge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GetRechargeRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetRechargeRecords) ProtoMessage() {}

func (x *S2C_GetRechargeRecords) ProtoReflect() protoreflect.Message {
	mi := &file_game_recharge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetRechargeRecords.ProtoReflect.Descriptor instead.
func (*S2C_GetRechargeRecords) Descriptor() ([]byte, []int) {
	return file_game_recharge_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_GetRechargeRecords) GetRecords() []*RechargeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_game_recharge_proto protoreflect.FileDescriptor

const file_game_recharge_proto_rawDesc = "" +
	"\n" +
	"\x13game/recharge.proto\x1a\x10message_id.proto\"\xdc\x01\n" +
	"\x0eRechargeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05bonus\x18\x04 \x01(\x03R\x05bonus\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\"\x8f\x03\n" +
	"\x0eRechargeRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\x05R\bplatform\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x19\n" +
	"\border_id\x18\b \x01(\tR\aorderId\x12%\n" +
	"\x0etransaction_id\x18\t \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\v \x01(\x03R\n" +
	"updateTime\x12#\n" +
	"\rcomplete_time\x18\f \x01(\x03R\fcompleteTime\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\"\x7f\n" +
	"\x13C2S_RechargeRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12,\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x10.PaymentPlatformR\bplatform\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\tR\bconfigId:\x05\x80\xb5\x18\xe9\a\"\xa6\x01\n" +
	"\x14S2C_RechargeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vpayment_url\x18\x04 \x01(\tR\n" +
	"paymentUrl\x12\x17\n" +
	"\aqr_code\x18\x05 \x01(\tR\x06qrCode:\x05\x80\xb5\x18\xcd\b\"\x8c\x01\n" +
	"\x13S2C_RechargeSuccess\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance:\x05\x80\xb5\x18\xce\b\"\x1f\n" +
	"\x16C2S_GetRechargeConfigs:\x05\x80\xb5\x18\xeb\a\"J\n" +
	"\x16S2C_GetRechargeConfigs\x12)\n" +
	"\aconfigs\x18\x01 \x03(\v2\x0f.RechargeConfigR\aconfigs:\x05\x80\xb5\x18\xcf\b\"5\n" +
	"\x16C2S_GetRechargeRecords\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit:\x05\x80\xb5\x18\xec\a\"J\n" +
	"\x16S2C_GetRechargeRecords\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.RechargeRecordR\arecords:\x05\x80\xb5\x18\xd0\b*c\n" +
	"\x0fPaymentPlatform\x12\x11\n" +
	"\rPlatform_None\x10\x00\x12\x13\n" +
	"\x0fPlatform_WeChat\x10\x01\x12\x13\n" +
	"\x0fPlatform_AliPay\x10\x02\x12\x13\n" +
	"\x0fPlatform_DouYin\x10\x03B\x0eZ\f./../messageb\x06proto3"

var (
	file_game_recharge_proto_rawDescOnce sync.Once
	file_game_recharge_proto_rawDescData []byte
)

func file_game_recharge_proto_rawDescGZIP() []byte {
	file_game_recharge_proto_rawDescOnce.Do(func() {
		file_game_recharge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_recharge_proto_rawDesc), len(file_game_recharge_proto_rawDesc)))
	})
	return file_game_recharge_proto_rawDescData
}

var file_game_recharge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_recharge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_recharge_proto_goTypes = []any{
	(PaymentPlatform)(0),           // 0: PaymentPlatform
	(*RechargeConfig)(nil),         // 1: RechargeConfig
	(*RechargeRecord)(nil),         // 2: RechargeRecord
	(*C2S_RechargeRequest)(nil),    // 3: C2S_RechargeRequest
	(*S2C_RechargeResponse)(nil),   // 4: S2C_RechargeResponse
	(*S2C_RechargeSuccess)(nil),    // 5: S2C_RechargeSuccess
	(*C2S_GetRechargeConfigs)(nil), // 6: C2S_GetRechargeConfigs
	(*S2C_GetRechargeConfigs)(nil), // 7: S2C_GetRechargeConfigs
	(*C2S_GetRechargeRecords)(nil), // 8: C2S_GetRechargeRecords
	(*S2C_GetRechargeRecords)(nil), // 9: S2C_GetRechargeRecords
}
var file_game_recharge_proto_depIdxs = []int32{
	0, // 0: C2S_RechargeRequest.platform:type_name -> PaymentPlatform
	1, // 1: S2C_GetRechargeConfigs.configs:type_name -> RechargeConfig
	2, // 2: S2C_GetRechargeRecords.records:type_name -> RechargeRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_game_recharge_proto_init() }
func file_game_recharge_proto_init() {
	if File_game_recharge_proto != nil {
		return
	}
	file_message_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_recharge_proto_rawDesc), len(file_game_recharge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_recharge_proto_goTypes,
		DependencyIndexes: file_game_recharge_proto_depIdxs,
		EnumInfos:         file_game_recharge_proto_enumTypes,
		MessageInfos:      file_game_recharge_proto_msgTypes,
	}.Build()
	File_game_recharge_proto = out.File
	file_game_recharge_proto_goTypes = nil
	file_game_recharge_proto_depIdxs = nil
}
