// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: BaseMessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SMessageId int32

const (
	C2SMessageId_C2S_NULL  C2SMessageId = 0
	C2SMessageId_C2S_LOGIN C2SMessageId = 1
)

// Enum value maps for C2SMessageId.
var (
	C2SMessageId_name = map[int32]string{
		0: "C2S_NULL",
		1: "C2S_LOGIN",
	}
	C2SMessageId_value = map[string]int32{
		"C2S_NULL":  0,
		"C2S_LOGIN": 1,
	}
)

func (x C2SMessageId) Enum() *C2SMessageId {
	p := new(C2SMessageId)
	*p = x
	return p
}

func (x C2SMessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2SMessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_BaseMessage_proto_enumTypes[0].Descriptor()
}

func (C2SMessageId) Type() protoreflect.EnumType {
	return &file_BaseMessage_proto_enumTypes[0]
}

func (x C2SMessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2SMessageId.Descriptor instead.
func (C2SMessageId) EnumDescriptor() ([]byte, []int) {
	return file_BaseMessage_proto_rawDescGZIP(), []int{0}
}

type S2CMessageId int32

const (
	S2CMessageId_S2C_NULL  S2CMessageId = 0
	S2CMessageId_S2C_LOGIN S2CMessageId = 1
)

// Enum value maps for S2CMessageId.
var (
	S2CMessageId_name = map[int32]string{
		0: "S2C_NULL",
		1: "S2C_LOGIN",
	}
	S2CMessageId_value = map[string]int32{
		"S2C_NULL":  0,
		"S2C_LOGIN": 1,
	}
)

func (x S2CMessageId) Enum() *S2CMessageId {
	p := new(S2CMessageId)
	*p = x
	return p
}

func (x S2CMessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2CMessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_BaseMessage_proto_enumTypes[1].Descriptor()
}

func (S2CMessageId) Type() protoreflect.EnumType {
	return &file_BaseMessage_proto_enumTypes[1]
}

func (x S2CMessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2CMessageId.Descriptor instead.
func (S2CMessageId) EnumDescriptor() ([]byte, []int) {
	return file_BaseMessage_proto_rawDescGZIP(), []int{1}
}

var File_BaseMessage_proto protoreflect.FileDescriptor

var file_BaseMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x2b, 0x0a, 0x0c, 0x43, 0x32,
	0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x32,
	0x53, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x2a, 0x2b, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x4e,
	0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BaseMessage_proto_rawDescOnce sync.Once
	file_BaseMessage_proto_rawDescData = file_BaseMessage_proto_rawDesc
)

func file_BaseMessage_proto_rawDescGZIP() []byte {
	file_BaseMessage_proto_rawDescOnce.Do(func() {
		file_BaseMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_BaseMessage_proto_rawDescData)
	})
	return file_BaseMessage_proto_rawDescData
}

var file_BaseMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_BaseMessage_proto_goTypes = []interface{}{
	(C2SMessageId)(0), // 0: proto.C2SMessageId
	(S2CMessageId)(0), // 1: proto.S2CMessageId
}
var file_BaseMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BaseMessage_proto_init() }
func file_BaseMessage_proto_init() {
	if File_BaseMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BaseMessage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BaseMessage_proto_goTypes,
		DependencyIndexes: file_BaseMessage_proto_depIdxs,
		EnumInfos:         file_BaseMessage_proto_enumTypes,
	}.Build()
	File_BaseMessage_proto = out.File
	file_BaseMessage_proto_rawDesc = nil
	file_BaseMessage_proto_goTypes = nil
	file_BaseMessage_proto_depIdxs = nil
}
