// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: BaseMessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageId int32

const (
	MessageId_NULL  MessageId = 0
	MessageId_LOGIN MessageId = 1
)

// Enum value maps for MessageId.
var (
	MessageId_name = map[int32]string{
		0: "NULL",
		1: "LOGIN",
	}
	MessageId_value = map[string]int32{
		"NULL":  0,
		"LOGIN": 1,
	}
)

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}

func (x MessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_BaseMessage_proto_enumTypes[0].Descriptor()
}

func (MessageId) Type() protoreflect.EnumType {
	return &file_BaseMessage_proto_enumTypes[0]
}

func (x MessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageId.Descriptor instead.
func (MessageId) EnumDescriptor() ([]byte, []int) {
	return file_BaseMessage_proto_rawDescGZIP(), []int{0}
}

var File_BaseMessage_proto protoreflect.FileDescriptor

var file_BaseMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x20, 0x0a, 0x09, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BaseMessage_proto_rawDescOnce sync.Once
	file_BaseMessage_proto_rawDescData = file_BaseMessage_proto_rawDesc
)

func file_BaseMessage_proto_rawDescGZIP() []byte {
	file_BaseMessage_proto_rawDescOnce.Do(func() {
		file_BaseMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_BaseMessage_proto_rawDescData)
	})
	return file_BaseMessage_proto_rawDescData
}

var file_BaseMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_BaseMessage_proto_goTypes = []interface{}{
	(MessageId)(0), // 0: proto.MessageId
}
var file_BaseMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BaseMessage_proto_init() }
func file_BaseMessage_proto_init() {
	if File_BaseMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BaseMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BaseMessage_proto_goTypes,
		DependencyIndexes: file_BaseMessage_proto_depIdxs,
		EnumInfos:         file_BaseMessage_proto_enumTypes,
	}.Build()
	File_BaseMessage_proto = out.File
	file_BaseMessage_proto_rawDesc = nil
	file_BaseMessage_proto_goTypes = nil
	file_BaseMessage_proto_depIdxs = nil
}
